---
stages:
- name: Build Stage
  inputs:
  - type: git
    branch: ${BRANCH}
    service: ${REPO}
  jobs:
  - name: Build
    type: builder
    artifact_dir: ''
- name: Deploy Stage
  inputs:
  - type: job
    stage: Build Stage
    job: Build
  triggers:
  - type: stage
  jobs:
  - name: Deploy
    type: deployer
    target:
      region_id: ${CF_REGION_ID}
      organization: ${CF_ORGANIZATION}
      space: ${CF_SPACE}
      application: ${CF_APP}
    script: |-
      #!/bin/bash
      if [ ${SETUP} = "true" ] ; then
        # Create Services
        cf create-service cloudantNoSQLDB Lite "${CUSTOM_APP_NAME}"-cloudant
        #Create autentication keys
        cf create-service-key "${CUSTOM_APP_NAME}"-cloudant cloudantKey
      fi

      cf push "${CF_APP}"
      # View logs
      # cf logs "${CF_APP}" --recent
      if [ ${SETUP} = "true" ] ; then
        # Bind Services
        cf bind-service "${CF_APP}" "${CUSTOM_APP_NAME}"-cloudant
        cf restage "${CF_APP}"
      fi
      if [ ${SETUP} = "true" ] ; then
        echo "*** BACKEND CREDENTIALS ***"
        cf service-key "${CUSTOM_APP_NAME}"-cloudant cloudantKey
      fi

      
